import java.util.Scanner;
import java.util.ArrayList;

public class RunNeuralNetwork
{
    //features
    private static Scanner userScanner = new Scanner ( System.in );
    private static NeuralNetwork neuralNetwork = new NeuralNetwork ( );
    
    public static void main ( String [ ] arguments )
    {
        doTraining ( );
        runMainMenu ( );
    }
    
    //methods
    public static void doTraining ( )
    {
        ArrayList <String> trainingData = getTrainingData ( );
        System.out.println ( "trainingData size : " + trainingData.size ( ) );
        
        for ( int tDI = 0; tDI < trainingData.size ( ); tDI ++ )
        {
            //forward propagation
            String inputLine = trainingData.get ( tDI ).split ( ":" ) [ 0 ];
            int in0 = Integer.parseInt ( inputLine.split ( "," ) [ 0 ] );
            int in1 = Integer.parseInt ( inputLine.split ( "," ) [ 1 ] );
            
            neuralNetwork.doForwardPropagation ( new int [ ] { in0, in1 } );
            
            //backward propagation
            int targetData = Integer.parseInt (  trainingData.get ( tDI ).split ( ":" ) [ 1 ] );
            
            neuralNetwork.doBackwardPropagation ( targetData );
        }
    }
    
    public static void returnToMain ( )
    {
        userScanner.nextLine ( );
        userScanner.nextLine ( );
        System.out.println ( "\f" );
        runMainMenu ( );
    }
    
    public static void runMainMenu ( )
    {
        System.out.println ( "G. Bennett Neural Network Practice 2024, February" );
        System.out.println ( "1. Get neural network estimation for input = [0,0] " );
        System.out.println ( "2. Get neural network estimation for input = [0,1] " );
        System.out.println ( "3. Get neural network estimation for input = [1,0] " );
        System.out.println ( "4. Get neural network estimation for input = [1,1] " );
        System.out.println ( "5. Get me out quick! " );
        System.out.println ( "Select an option " );
        
        
        int userInput = userScanner.nextInt ( );
        
        switch ( userInput )
        {
            case 1 :
            {
                int [ ] input = new int [ ] { 0, 0 };
                neuralNetwork.doForwardPropagation ( input );
                double neuralNetworkOutput = neuralNetwork.getOutcome ( );
                System.out.println ( "Neural network estimation for outout { 0 , 0 } is : " + neuralNetworkOutput );
                returnToMain ( );
            }
            break;
            
            case 2 :
            {
                int [ ] input = new int [ ] { 0, 1 };
                neuralNetwork.doForwardPropagation ( input );
                double neuralNetworkOutput = neuralNetwork.getOutcome ( );
                System.out.println ( "Neural network estimation for outout { 0 ,1 } is : " + neuralNetworkOutput );
                returnToMain ( );
            }
            break; 
            
            case 3 :
            {
                int [ ] input = new int [ ] { 1, 0 };
                neuralNetwork.doForwardPropagation ( input );
                double neuralNetworkOutput = neuralNetwork.getOutcome ( );
                System.out.println ( "Neural network estimation for outout { 1 , 0 } is : " + neuralNetworkOutput );
                returnToMain ( );
            }
            break;
            
            case 4 :
            {
                int [ ] input = new int [ ] { 1, 1 };
                neuralNetwork.doForwardPropagation ( input );
                double neuralNetworkOutput = neuralNetwork.getOutcome ( );
                System.out.println ( "Neural network estimation for outout { 1 ,1 } is : " + neuralNetworkOutput );
                returnToMain ( );
            }
            break; 
            
            case 5 :
            {
                System.exit ( 0 );
            }
            break; 
        }
    }
    
    
    public static ArrayList <String> getTrainingData ( ) 
    {
        ArrayList <String> returnValue = new ArrayList <String> ( );
        
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        returnValue.add ( "0,0:0" );
        returnValue.add ( "0,1:1" );
        returnValue.add ( "1,0:1" );
        returnValue.add ( "1,1:0" );
        
        
        return returnValue;
    }
}
